askdjango/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.profile, name='profile'),
]
# cbv에서는 template 연결을 이런 식으로 한다.
# 설정해주지 않으면 default로 class LoginView의 registration/login.html 로 설정이 되어 있는데,
# 이 경로에 만들어줘도 된다.

# accounts/login이라고 설정한 이유는 있다.
# 만약 blog 앱의 views.py에서
#
# from django.contrib.auth.decorators import login_required
# @login_required
# def post_new(request):
# pass

# 라고 했을 때, 로그인이 안 되어 있을 때는
# django/conf/global_settings.py에 있는
# LOGIN_URL = '/accounts/login/' 쪽으로 간다.
# 그렇기 때문에 앱이름도 accounts, projects url도 accounts라고 설정한 것.

# 여기서 superuser로 로그인 하면 page not found하면서 url이 /accounts/profile/이 뜨는데,
# 이는 디폴트로 아래와 같이 설정되어 있기 때문이다.
# LOGIN_REDIRECT_URL = '/accounts/profile/'

# reverse_lazy(): settings에 reverse가 있으면 초기화되는 과정에서 url reverse를 하기 때문에 실패하게 됨
# 그래서 이는 reverse_lazy는 실제 url을 참조하게 될 때 사용하게 됨. 게으르게.
# 그렇기에 global_settings에 reverse를 사용할 때는 reverse_lazy사용
# -->
# LOGIN_URL = '/accounts/login/'
# LOGIN_URL = reverse_lazy('login')

# LOGIN_REDIRECT_URL = '/accounts/profile/'
# LOGIN_REDIRECT_URL = reverse_lazy('profile')

askdjango/askdjango/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('', lambda req: redirect('/blog/'), name="root"),
    # 최상위 주소로 갈 시 redirect
]

askdjango/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:pk>', views.post_detail, name='post_detail'),
]

askdjango/accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.conf import settings

# 유저에 대한 정보가 별로 없으니 profile을 직접만들어보자!
# 근데 onetoonefield인데, profile model을 생성하고 migrate해버리면
# 기존에 있었던 user들은 profile이 없게 된다!
# 그러면 migrations파일에 들어가서, migrate하자마자 현재 db에 등록되어 있는 user들에 대해서도 만들어주려 한다.
# migrations 파일로 가자. 공식문서 가면 RunPython 부분이 있다.

# 또한 회원가입 동시에 user객체가 만들어지면 profile이 생성되도록 만들어야 한다.
# django post_save, signal을 써보자


class Profile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    website_url = models.URLField(blank=True)


def on_post_save_for_user(sender, **kwargs):
    if kwargs['created']:
        user = kwargs['instance']
        Profile.objects.create(user=user)


post_save.connect(on_post_save_for_user, sender=settings.AUTH_USER_MODEL)

askdjango/blog/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

askdjango/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login as auth_login


# 로그아웃 상황일 때는 login url로 이동시켜 준다. 그래서 로그아웃 상태에서 /accounts/profile/ 접속해도 로그인 페이지로 redirect된다.
@login_required
def profile(request):
    return render(request, 'accounts/profile.html')


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()  # 이 시점이 db 저장. 즉 객체 생성
            # 이 시점에서 회원가입하면 자동 로그인 처리하기
            # django/contrib/auth/LoginView에 form_valid가 있음.
            # 이는 form.is_valid일 때 호출되는 함수
            # import하고, form_valid인자로 request와 user를 넘겨주면 로그인 시킴
            auth_login(request, user)
            next_url = request.GET.get('next') or 'profile'
            # return redirect('login')
            # return redirect('profile')  # 회원가입하면 profile로 바로 이동
            return redirect(next_url)
    else:
        form = UserCreationForm()
    return render(request, "accounts/signup.html/", {'form': form, })

# CBV
# from django.views.generic import CreateView
# from django.contrib.auth.models import User
# from django.conf import settings


# signup = CreateView.as_view(model=User, form_class=UserCreationForm, success_url='settings.LOGIN_URL', template_name='accounts/signup.html')


# 회원가입하면 자동 로그인
# class SignupView(CreateView):
#     model=User
#     form_class=SignupForm
#     template_name="accounts/signup.html"

#     def get_success_url(self):
#         next_url = self.request.GET.get('next') or 'profile'
#         return resolve_url(next_url) # import 해야함

#     def form_valid(self,form):
#         user=form.save()
#         auth_login(self.request,user)
#         return redirect('profile')

# signup=SignupView.as_view()

askdjango/blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Post

post_list = ListView.as_view(model=Post)
post_detail = DetailView.as_view(model=Post)

askdjango/accounts/templates/accounts/layout.html
{% extends "layout.html" %}

askdjango/accounts/templates/accounts/login.html
<form action="" method = "POST">
    {% csrf_token %}
    <table>
        {{form.as_table}}
    </table>
    <input type ="submit" />
</form>

askdjango/accounts/templates/accounts/profile.html
{% extends "accounts/layout.html" %}
{% block content %}
    <h2>{{user}}'s Profile</h2>
    <h2>Bio</h2>
    {{user.profile.bio|default:"empty"}}
{% endblock %}

askdjango/accounts/templates/accounts/signup.html
{% extends "accounts/layout.html" %}

{% block content%}
    <form action="" method = "POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type ="submit" />
    </form>
{% endblock%}

askdjango/askdjango/templates/layout.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>AskDjango Blog</title>
    {% block extra_head %}{% endblock %}
  </head>
  <body>
    <a href= "{% url "root" %}"><h1>Askdjango Blog</h1></a>
    <hr/>
    <!--django/contrib/auth/context_processors 에서 바로 사용할 수 있는 변수목록을 정의. 그 중에 하나가 user-->
    {% if user.is_authenticated %}
      <a href="{% url "profile" %}">{{user}}</a>  
      <a href="{% url "logout" %}?next={{ request.path }}" onclick="return confirm('Are you sure?');">로그아웃</a>
    <!--logout이라고만 revername을 적으면, 관리자 페이지로 넘어가게 됨-->
    {% else %}
      <a href="{% url "signup" %}?next={{ request.path }}">회원가입</a>
      <a href="{% url "login" %}?next={{request.path}}">로그인</a> <!--여기서 namespace쓰지 않는 이유는 accounts에서 app_name 지정 안 했기 때문이다.-->
    <!--로그인을 누르면 현재 주소가 넘어가게 되고, 로그인 성공하면 다시 원래 페이지로 돌아옴. -->
    {% endif %}

    <hr/>
    {% block content %} {% endblock %}

    <hr />
    &copy: 2018. Askdjango
  </body>
</html>

askdjango/blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block content %}
    <h2>{{post.title}}</h2>
    {{post.content|linebreaks}}

    <hr />
    <a href ="{% url "blog:post_list" %}">글 목록</a>
{% endblock %}

askdjango/blog/templates/blog/post_list.html
{% extends "blog/layout.html" %} 
{% block content %}
<table>
  <tbody>
    {% for post in post_list %}
    <tr>
      <td>
        <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}