askcompany/askcompany/urls.py
from django.contrib import admin
from django.http import HttpResponse
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),  # 어떤 url이 오면 어떤 함수를 호출하겠다.
    path('shop/', include('shop.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

askcompany/blog/urls.py
from django.urls import path

app_name = 'blog'

urlpatterns = [
]

askcompany/shop/urls.py
from django.urls import path, register_converter
from .converters import FourDigitYearConverter
from . import views

register_converter(FourDigitYearConverter, 'yyyy')

app_name = 'shop'

urlpatterns = [
    path('archives/<yyyy:year>/', views.archives_year, name="archives_year"),
    path('', views.item_list, name="item_list"),
    path('<int:pk>/', views.item_detail, name="item_detail"),
    # re_path(r'^(?P<pk>\d+)/$'), views.item_detail),
    path('new/', views.item_new, name="item_new"),
    path('<int:pk>/edit/', views.item_edit, name="item_edit"),
]

askcompany/blog/models.py
from django.db import models
from askcompany.utils import uuid_upload_to
# Create your models here.


class Post(models.Model):
    author_name = models.TextField(max_length=20)
    title = models.CharField(max_length=100)
    content = models.TextField()
    photo = models.ImageField(upload_to=uuid_upload_to)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)


class Comment(models.Model):
    # post가 삭제되면 참조값 같이 삭제.
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    message = models.TextField()


# Post.objects.all().count() --> 0
# post1 = Post.objects.create(author_name="author1", title="title1", content="content1")
# Comment.objects.all().count() --> 0
# Comment.objects.create(post=post1, message="django")
# Comment.objects.create(post=post1, message="fucking")
# Comment.objects.create(post=post1, message="hard")
# Comment.objects.all().count()
# post1.comment_set.all()
# Comment.objects.filter(post=post1)

askcompany/shop/models.py
from django.db import models
from django.urls import reverse
from askcompany.utils import uuid_upload_to
# from django.conf import settings


class Item(models.Model):
    name = models.CharField(max_length=100, validators=[])
    desc = models.TextField(blank=True)
    price = models.PositiveIntegerField()
    photo = models.ImageField(blank=True, upload_to=uuid_upload_to)
    is_published = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'<{self.pk}> {self.name}'

    def get_absolute_url(self):
        return reverse('shop:item_detail', kwargs={'pk': self.pk})


# class Profile(models.Model):
#     user = models.OneToOneField(
#         settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     blog_url = models.URLField(blank=True)


# class Post(models.Model):
#     author = models.ForeignKey(
#         settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     title = models.CharField(max_length=100, db_index=True)
#     slug = models.SlugField(allow_unicode=True)  # 한글을 지원하기 위함
#     desc = models.TextField(blank=True)
#     image = models.ImageField(blank=True)
#     comment_count = models.PositiveIntegerField(default=0)
#     tag_set = models.ManyToManyField('Tag', blank=True)
#     is_publish = models.BooleanField(default=False)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

# class Comment(models.Model):
#     author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     post = models.ForeignKey(POST, on_delete=models.CASCADE)
#     message = models.TextField()
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

# class Tag(models.Model):
#     name = models.CharField(max_length=50, unique=True)

askcompany/shop/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'

askcompany/shop/views.py
from django.shortcuts import get_object_or_404, redirect, render
import logging
from django.shortcuts import render, get_object_or_404, redirect
import re
from django.http import HttpResponse
from .models import Item
from .forms import ItemForm


def archives_year(request, year):
    return HttpResponse('{}년도에 대한 내용'.format(year))


def item_list(request):
    items = Item.objects.all()
    # get인자에서 가져옴. word를 가져오는데, 없으면 빈 것을 반환하겠다
    word = request.GET.get('word', '')
    if word:  # 즉 검색어가 있다면.
        # i = ignore, 즉 알파벳일 경우에는 대소문자를 구분하지 않겠다.
        items = items.filter(name__icontains=word)
    return render(request, 'shop/item_list.html', {'items': items, 'word': word})


def item_detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return render(request, 'shop/item_detail.html', {'item': item})


# def item_new(request):
#     print('Get:', request.GET)
#     print('POST:', request.POST) dict 형태. value는 list형식 반환: ex. 'name':[입력값]
#     print('FILES:', request.FILES)
#     return render(request, 'shop/item_form.html')


# logger = logging.getLogger(__name__)  # __name__ => "shop.views"


# def item_new(request, item=None):
#     error_list = []
#     initial = {}

#     if request.method == 'POST':
#         data = request.POST
#         files = request.FILES

#         name = data.get('name')
#         desc = data.get('desc')
#         price = data.get('price')
#         photo = files.get('photo')
#         is_publish = data.get('is_publish') in (True, 't', 'True', '1')

#         # 유효성 검사
#         if len(name) < 2:
#             error_list.append('name을 2글자 이상 입력해주세요.')

#         if re.match(r'^[\da-zA-Z\s]+$', desc):
#             error_list.append('한글을 입력해주세요.')

#         if not error_list:
#             # 저장 시도
#             if item is None:
#                 item = Item()

#             item.name = name
#             item.desc = desc
#             item.price = price
#             item.is_publish = is_publish

#             if photo:
#                 item.photo.save(photo.name, photo, save=False)

#             try:
#                 item.save()
#             except Exception as e:
#                 error_list.append(e)
#             else:
#                 return redirect(item)

#         initial = {
#             'name': name,
#             'desc': desc,
#             'price': price,
#             'photo': photo,
#             'is_publish': is_publish,
#         }
#     else:
#         if item is not None:
#             initial = {
#                 'name': item.name,
#                 'desc': item.desc,
#                 'price': item.price,
#                 'photo': item.photo,
#                 'is_publish': item.is_publish,
#             }

#     return render(request, 'shop/item_form.html', {
#         'error_list': error_list,
#         'initial': initial,
#     })


# def item_edit(request, pk):
#     item = get_object_or_404(Item, pk=pk)
#     return item_new(request, item)


def item_new(request, item=None):
    if request.method == 'POST':
        # 순서 중요, instance는 ModelForm지원기능
        form = ItemForm(request.POST, request.FILES, instance=item)
        if form.is_valid():
            item = form.save()  # ModelFrom에서 제공
            return redirect(item)
    else:
        form = ItemForm(instance=item)

    return render(request, 'shop/item_form.html', {'form': form, })


def item_edit(request, pk):
    item = get_object_or_404(Item, pk=pk)
    return item_new(request, item)

# item_new = CreateView.as_view(model=Item, form_class=ItemForm)
# item_edit = UpdateView.as_view(model=Item, form_class=ItemForm)

askcompany/askcompany/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Ask Company {% endblock %}</title>
    <style>
        body {background-color: lightpink;}
    </style>
    {% block extra_head %}
    <link rel="stylesheet" href="{% static "main.css" %}" />
    {% endblock %}
</head>
<body>
    <h1> Ask Company</h1>

    {% block content %}
    {% endblock %}
    <hr/>
    copy: 2021, Ask Company
    {% block extra_body %}
        <script src="{% static "main.js" %}"></script>
    {% endblock %}
</body>
</html>

askcompany/blog/templates/blog/layout.html
{% extends "layout.html" %}
{% block title %} Blog by Ask Company {% endblock %}

askcompany/shop/templates/shop/item_detail.html
{% extends "shop/layout.html" %}
{% load humanize %}

{% block content %}
    <h2>{{item.name}}</h2>
    
    {% if item.photo %}
        {{ item.photo }} <br />
        <img src="{{item.photo.url}}" style="max-width : 80%"/><br /> 
        {{ item.photo.path }}<br />
    {% endif %}

    가격: {{ item.price|intcomma }}원

    {% if item.desc %}
        <p>
            {{item.desc}}
        </p>
    {% endif %}

    <hr />
    <a href="{% url "shop:item_list" %}">목록</a>
    <a href="{% url "shop:item_edit" item.pk %}">수정</a>
{% endblock %}

askcompany/shop/templates/shop/item_form.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8" />
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />
    </head>
    <body>
        <div class="container">
            <div class="col-sm-12">

                <h2>New Item</h2>
                <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
                    {% csrf_token %}
                    <table class = "table table-bordered">
                        {{ form.as_table }}
                    </table>
                    <input type="submit" value="저장하기" class="btn btn-primary" />
                </form>

            </div>
        </div>
    </body>
</html>

askcompany/shop/templates/shop/item_list.html
{% extends "shop/layout.html" %}

{% block content %}
    <form action="" method ="GET">
        <input type= "text" name ="word" value = "{{ word }}" />
        <input type= "submit" value="search" />
    </form>
    <ul>
        {% for item in items %}
            <li>
                <!-- <a href="/shop/{{item.pk}}"> -->
                <a href="{{item.get_absolute_url}}">
                {{item.name}}
                </a>
                {{item.price}}
                {{item.desc}}
            </li>
        {% endfor %}
    </ul>
    <hr/>
    <a href="{% url "shop:item_new" %}">New Item</a>    
{% endblock %}

askcompany/shop/templates/shop/layout.html
{% extends "layout.html" %}
{% block title %} Shop by Ask Company {% endblock %}

{% block extra_head %}
    {{ block.super }}
{% endblock %}

{% block extra_body %}
    {{ block.super }}
{% endblock %}